[build]
  command = "npm install"
  publish = "public"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/weather"
  to = "/.netlify/functions/weather"
  status = 200

[[redirects]]
  from = "/api/analyze"
  to = "/.netlify/functions/analyze"
  status = 200

[[redirects]]
  from = "/api/export"
  to = "/.netlify/functions/export"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"